// backend/tests/__mocks__/mockAnalysisResponse.js

module.exports = {
  items: [
    {
      name: "Milk",
      quantity: 1,
      totalCalories: 150,
      macronutrients: {
        proteins: 8,
        carbohydrates: 12,
        fats: 8,
        sodium: 100,
        cholesterol: 20,
        waterContent: 90,
        omega3: 0,
        omega6: 0,
        solubleFiber: 0,
        insolubleFiber: 0,
      },
      micronutrients: {
        VitaminA: 500,
        VitaminC: 0,
        VitaminD: 100,
        VitaminE: 1,
        VitaminK: 0,
        VitaminB12: 3,
        VitaminB6: 0.5,
        Folate: 50,
        Calcium: 300,
        Iron: 0,
        Magnesium: 10,
        Zinc: 1,
        Selenium: 5,
        Polyphenols: 0,
        Antioxidants: 0,
        Fiber: 0,
        Sugar: 12,
      },
      glycemicIndex: 30,
      glycemicLoad: 5,
      actualExpirationDate: "2024-06-30",
      estimatedExpirationDate: "2024-06-30",
      unit: "liters",
      confidence: 95,
      category: "Dairy"
    },
    {
      name: "Eggs",
      quantity: 12,
      totalCalories: 70,
      macronutrients: {
        proteins: 6,
        carbohydrates: 1,
        fats: 5,
        sodium: 70,
        cholesterol: 185,
        waterContent: 75,
        omega3: 1,
        omega6: 1,
        solubleFiber: 0,
        insolubleFiber: 0,
      },
      micronutrients: {
        VitaminA: 300,
        VitaminC: 0,
        VitaminD: 20,
        VitaminE: 0.5,
        VitaminK: 0,
        VitaminB12: 1.1,
        VitaminB6: 0.1,
        Folate: 24,
        Calcium: 28,
        Iron: 1.2,
        Magnesium: 5,
        Zinc: 0.6,
        Selenium: 15.4,
        Polyphenols: 0,
        Antioxidants: 0,
        Fiber: 0,
        Sugar: 0,
      },
      glycemicIndex: 0,
      glycemicLoad: 0,
      actualExpirationDate: "2024-07-10",
      estimatedExpirationDate: "2024-07-10",
      unit: "dozen",
      confidence: 92,
      category: "Protein"
    }
  ],
  categoriesSummary: {
    Dairy: 1,
    Protein: 1
  },
  errors: []
};
